language: python
python:
- '3.6'
- '3.7'
install: pip install -r requirements-dev.txt
script: make test-and-lint
deploy:
  provider: pypi
  python: '3.6'
  user: kobybum
  password:
    secure: G6jAj+4+4NOud+lqPyfaW4VqpU2d0kUkvdgzjRsu/t3EsI3M2VjluB3dMsZKOQlTTpPZGrGfH2pE/TPuIxeLXBQBABpOz6ZK/MycSMy1HJqLVOCV2/qVHhwHCtMtIwf0t7zSG5N0kQFd7TtHCDQucuQUstrBVkvHci7uDCcA1LMMNZTFbqXLUBHYRefR5E9LVD0IC2adZDedqTKrLToQSpE4W7Zfg4WPOVbCjTQRO2l5kqqpxhGun5qEMTTimAcTD9Q/Jj7EKMOVwZZWWcbbbJlTDOJPnXSZXJQd+WwZVvuRo7tpeyCCZaQS3ibW3e316lmJWAxFfTkOT4hffleMOP5/wan9ZPs8FRTSO/61MeRUIyLXLcvjBv0vnr/Uq2IT2gc1aPXgJjZNZSW2/uizQORcoizgBSnm3ZYLBnKRE9p6hhunWceVeb/QdNr/U0ul1p+FeBtTjemAb0WWJBwOJBPceSPlBrgc5kScZGhF7YewTENga6FGrtfxqkv46NJ4bXQYwyDdyW7hBarzH9njtJYPiQgnveu0CEAnTfZX59MXfgOTjqTu0/HIOcFCQwedTHda8VVLgWsLFOGvMKTDfunvqXzelaRoxTDhLItqP6YVWXuD1s/Kb9XHddPgDW5IP1WQTSG+rIyZgNBNF3OS1S0t9L+88SFl2pNH3u1XyBs=
  on:
    tags: true
    python: '3.6'
